# Site settings
title: Kun's Blog
SEOTitle: 袋底洞 | Kun's Blog
header-img: img/post-bg-desk.jpg
email: yakun.zhao712@gmail.com
description: "Stay hungry. Stay foolish"
keyword: "Kun, Yakun, 亚坤， 赵亚坤"
url: "http://yakunzhao712.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yakunzhao712/yakunzhao712.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "To cure sometimes; \nTo relieve often; \nTo comfort always"
sidebar-avatar: /img/doge.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     kun-xian-sen
github_username:    yakunzhao712
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: yakun_zhao

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f84e20a35e69ab749a4e                            #生成的clientID
  clientSecret: e6fcca6ad6cafe1505b2f09fa8e1bd2f05684b39    #生成的clientSecret
  repo: yakunzhao712.github.io    #仓库名称
  owner: yakunzhao712    #github用户名
  admin: yakunzhao712
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 3e43da1fab2397892663f9eed9c01aeb

# Google Analytics
ga_track_id: 'UA-169913466-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
]
